/**
 * Regenerate shared/regionWater.data.json from the ABS water-use data cube.
 *
 *   npm run import:abs-water -- path/to/WUAFDCLGA202021.xlsx
 *
 * Download it from the ABS "Water Use on Australian Farms, 2020-21" release ("Agricultural water use
 * and irrigation water sources estimates by 2021 Local Government Areas"). The LGA for each district
 * is set in data/abs/districts.json.
 */
import ExcelJS from 'exceljs';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { districtWater, WATER_ITEMS, type WaterRow } from '../shared/absWaterImport';

const file = process.argv[2];
if (!file) {
  console.error('Usage: npm run import:abs-water -- path/to/WUAFDCLGA202021.xlsx');
  process.exit(1);
}

interface District { presetId: string; lga: Record<string, string> }
const districts = (JSON.parse(await readFile(path.resolve('data/abs/districts.json'), 'utf8')) as { districts: District[] }).districts;
const wanted = new Set(districts.flatMap((d) => Object.keys(d.lga)));
const items = new Set<string>(Object.values(WATER_ITEMS).flatMap((g) => Object.values(g)));

const text = (v: ExcelJS.CellValue): string => {
  if (v == null) return '';
  if (typeof v === 'object' && 'richText' in v) return v.richText.map((t) => t.text).join('');
  if (typeof v === 'object' && 'result' in v) return String(v.result ?? '');
  return String(v);
};

const rows: WaterRow[] = [];
let cols: Record<string, number> | null = null;

const reader = new ExcelJS.stream.xlsx.WorkbookReader(path.resolve(file), { sharedStrings: 'cache', worksheets: 'emit' });
for await (const sheet of reader) {
  // @ts-expect-error exceljs exposes `name` on the streamed worksheet reader
  if (sheet.name !== 'Table 1') continue;
  for await (const row of sheet) {
    // row.values is sparse; Array.from fills the holes.
    const values = Array.from(row.values as ExcelJS.CellValue[], text);
    if (!cols) {
      const i = values.findIndex((v) => (v ?? '').trim() === 'Region code');
      if (i >= 0) {
        const find = (label: string) => values.findIndex((v) => (v ?? '').trim().startsWith(label));
        cols = { code: i, label: find('Region label'), item: find('Commodity code'), est: find('Estimate') };
        if (Object.values(cols).some((c) => c < 0)) throw new Error(`Unexpected header row: ${values.join(' | ')}`);
      }
      continue;
    }
    const at = (i: number) => values[i] ?? '';
    const code = at(cols.code).trim().replace(/\.0$/, '');
    const item = at(cols.item).trim();
    if (!wanted.has(code) || !items.has(item)) continue;
    const raw = at(cols.est).trim();
    const est = raw === '' ? NaN : Number(raw);
    rows.push({ regionCode: code, regionLabel: at(cols.label), itemCode: item, estimate: Number.isFinite(est) ? est : null });
  }
}

if (!cols) throw new Error('Could not find the "Region code" header row in Table 1. Is this the WUAFDCLGA202021 file?');
const missing = [...wanted].filter((c) => !rows.some((r) => r.regionCode === c));
if (missing.length) throw new Error(`These LGA codes from data/abs/districts.json are not in the file: ${missing.join(', ')}`);

const regions = districts.map((d) => districtWater(rows, d.presetId, d.lga));
await writeFile(
  path.resolve('shared/regionWater.data.json'),
  JSON.stringify({ _readme: 'GENERATED by scripts/import-abs-water.ts from ABS WUAFDCLGA202021.xlsx. Do not edit by hand.', regions }, null, 2) + '\n',
);
for (const r of regions) {
  const f = (x: typeof r.orchards) => (x ? `${x.areaHa.toLocaleString('en-AU')} ha, ${x.mlPerHa ?? 'n/a'} ML/ha` : 'none');
  console.log(`  ${r.presetId.padEnd(14)} orchards ${f(r.orchards).padEnd(22)} vines ${f(r.vines)}`);
}
