/**
 * Regenerate shared/regionCrops.data.json from the ABS Agricultural Commodities data cube.
 *
 *   npm run import:abs -- path/to/AGCDCASGS202021.xlsx
 *
 * Download the file from the ABS "Agricultural Commodities, Australia, 2020-21" release:
 * "Agricultural commodities, Australia and state/territory and ASGS regions - 2020-21".
 * Which SA2 areas make up each district is set in data/abs/districts.json.
 */
import ExcelJS from 'exceljs';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { districtCrops, type AbsRow, type District } from '../shared/absRegionImport';

const file = process.argv[2];
if (!file) {
  console.error('Usage: npm run import:abs -- path/to/AGCDCASGS202021.xlsx');
  process.exit(1);
}

const districts = (JSON.parse(await readFile(path.resolve('data/abs/districts.json'), 'utf8')) as { districts: District[] }).districts;
const wanted = new Set(districts.flatMap((d) => Object.keys(d.sa2)));

const text = (v: ExcelJS.CellValue): string => {
  if (v == null) return '';
  if (typeof v === 'object' && 'richText' in v) return v.richText.map((t) => t.text).join('');
  if (typeof v === 'object' && 'result' in v) return String(v.result ?? '');
  return String(v);
};

const rows: AbsRow[] = [];
let cols: Record<string, number> | null = null;
let scanned = 0;

const reader = new ExcelJS.stream.xlsx.WorkbookReader(path.resolve(file), { sharedStrings: 'cache', worksheets: 'emit' });
for await (const sheet of reader) {
  // Only "Table 1" holds the data; other sheets are contents and notes.
  // @ts-expect-error exceljs exposes `name` on the streamed worksheet reader
  if (sheet.name !== 'Table 1') continue;
  for await (const row of sheet) {
    // row.values is sparse (index 0 unused, empty cells are holes); Array.from fills the holes.
    const values = Array.from(row.values as ExcelJS.CellValue[], text);
    if (!cols) {
      const i = values.findIndex((v) => v.trim() === 'Region code');
      if (i >= 0) {
        const find = (label: string) => values.findIndex((v) => v.trim().startsWith(label));
        cols = {
          code: i,
          label: find('Region label'),
          desc: find('Commodity description'),
          est: find('Estimate'),
          rse: find('Estimate - Relative Standard Error'),
        };
        if (Object.values(cols).some((c) => c < 0)) throw new Error(`Unexpected header row: ${values.join(' | ')}`);
      }
      continue;
    }
    scanned++;
    // Footnote rows at the end of the table are shorter than the header, so guard every read.
    const at = (i: number) => values[i] ?? '';
    const code = at(cols.code).trim().replace(/\.0$/, '');
    if (!wanted.has(code)) continue;
    const raw = at(cols.est).trim();
    const est = raw === '' ? NaN : Number(raw);
    rows.push({
      regionCode: code,
      regionLabel: at(cols.label),
      description: at(cols.desc),
      estimate: Number.isFinite(est) ? est : null,
      rse: at(cols.rse),
    });
  }
}

if (!cols) throw new Error('Could not find the "Region code" header row in Table 1. Is this the AGCDCASGS202021 file?');
const missing = [...wanted].filter((c) => !rows.some((r) => r.regionCode === c));
if (missing.length) throw new Error(`These SA2 codes from data/abs/districts.json are not in the file: ${missing.join(', ')}`);

const regions = districts.map((d) => districtCrops(rows, d));
const out = {
  _readme:
    'GENERATED by scripts/import-abs-region-crops.ts from ABS AGCDCASGS202021.xlsx. Do not edit by hand: change data/abs/districts.json or the commodity mapping in shared/absRegionImport.ts and re-run `npm run import:abs`.',
  regions,
};
await writeFile(path.resolve('shared/regionCrops.data.json'), JSON.stringify(out, null, 2) + '\n');

console.log(`Scanned ${scanned.toLocaleString('en-AU')} rows, used ${rows.length.toLocaleString('en-AU')} from ${wanted.size} SA2 areas.`);
for (const r of regions) {
  const list = r.grownToday.map((g) => `${g.name}${g.caution ? '*' : ''}`).join(', ') || `(none: ${r.note})`;
  console.log(`  ${r.presetId.padEnd(14)} ${list}`);
}
console.log('* = ABS "use with caution" estimate');
